menu:
  Home: /
  Archives: /blog/archives

widgets:
- search
- about
- category
- tagcloud
- recent_posts

excerpt_link: Read More

twitter:
  username: brianfive
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-1742529-10
rss: http://feeds.feedburner.com/evolvingbits

# comment_provider: facebook
# # Facebook comment
# facebook:
#   appid: 123456789012345
#   comment_count: 5
#   comment_width: 840
#   comment_colorscheme: light